/********************************************
Difficulty: Hard
Title: Bit Array
Author: Cavan Ray Theiss

Description: 

Count the number of distinct integers in a 
sequence generated by using the provided
four integers N, S, P, & Q

Use them to make a sequence with this rule:

First number is S mod 2^31.

Each next number = (previous * P + Q) mod 2^31.

Now, from the first N numbers you generate, just count how many are different and print that number.

When the problem says “mod 2³¹”, it means you take the remainder after dividing by 2^31.

2^31 = 2147483648.

So “x mod 2³¹” means “the remainder when x is divided by 2147483648.”

For example:

5 mod 2^31 = 5 (because 5 is smaller).

2147483649 mod 2^31 = 1.
********************************************/

#include <cmath>
#include <cstdio>
#include <vector>
#include <iostream>
#include <algorithm>
using namespace std;

int main() {
    /* Enter your code here. Read input from STDIN. Print output to STDOUT */   
    return 0;
}
