/********************************************
Difficulty: Hard
Title: Bit Array
Author: Cavan Ray Theiss

Description: 
Count the number of distinct integers in a 
sequence generated by using the provided
four integers N, S, P, & Q
********************************************/

#include <iostream>
#include <bitset>
#define MULT 2147483648LL

int main() {
    long long previous = 0, current = 0, N, S, P, Q;
    std::cin >> N >> S >> P >> Q;
    std::bitset<MULT> alreadySeen;
    for(int i = 0; i < N; i++){
        if(i == 0){
            current = (S % MULT);
        }else{
            current = (((previous * P) + Q) % MULT);
        }
        alreadySeen.set(current);
        previous = current;
    }
    std::cout << distinctMembers.size() << std::endl;
    return 0;
}
